interface ExplanationPanelProps {
  text: string;
  isDemoData?: boolean;
}

export function ExplanationPanel({ text, isDemoData = true }: ExplanationPanelProps) {
  return (
    <div className="border border-border bg-background">
      <div className="flex items-center justify-between border-b border-border px-6 py-4">
        <p className="label-mono">Analysis explanation</p>
        {isDemoData && (
          <span className="font-mono text-[0.65rem] tracking-[0.14em] text-muted-foreground">
            ILLUSTRATIVE EXPLANATION
          </span>
        )}
      </div>

      <div className="px-6 py-6">
        {isDemoData && (
          <div className="mb-5 border-l-2 border-border-strong pl-4">
            <p className="text-[0.75rem] text-muted-foreground leading-relaxed">
              The explanation below is illustrative only and was not generated by
              a real AI model or backend analysis system.
            </p>
          </div>
        )}
        <p className="text-[0.9rem] leading-relaxed text-muted-foreground">{text}</p>
      </div>
    </div>
  );
}
