"""
Configuration constants and paths for SYNAPS (SIH26147).
"""

from project_paths import (
    PROJECT_ROOT,
    DATA_ROOT,
    IQ_ROOT,
    WAV_ROOT,
    METADATA_ROOT,
    PROCESSED_ROOT,
    MODELS_ROOT,
    AI_MODELS_ROOT,
    TRANSFORMER_CHECKPOINT,
    RESULT_ROOT,
    TRANSFORMER_RESULT_DIR,
    CLASS_NAMES,
    CLASS_TO_INDEX,
    INDEX_TO_CLASS,
    normalize_modulation_name,
    resolve_sample_paths,
)

DEFAULT_SAMPLING_RATE = 1_000_000.0
DEFAULT_SAMPLES_PER_SYMBOL = 10
DEFAULT_SEQUENCE_LENGTH = 1000
DEFAULT_CONFIDENCE_THRESHOLD = 0.70
