/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as ProcessingRouteImport } from './routes/processing'
import { Route as ResultsRouteImport } from './routes/results'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessingRoute = ProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/processing': typeof ProcessingRoute
  '/results': typeof ResultsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/processing': typeof ProcessingRoute
  '/results': typeof ResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/processing': typeof ProcessingRoute
  '/results': typeof ResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/analyze' | '/processing' | '/results'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analyze' | '/processing' | '/results'
  id: '__root__' | '/' | '/analyze' | '/processing' | '/results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzeRoute: typeof AnalyzeRoute
  ProcessingRoute: typeof ProcessingRoute
  ResultsRoute: typeof ResultsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processing': {
      id: '/processing'
      path: '/processing'
      fullPath: '/processing'
      preLoaderRoute: typeof ProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzeRoute: AnalyzeRoute,
  ProcessingRoute: ProcessingRoute,
  ResultsRoute: ResultsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
